version: '{build}'

os: Visual Studio 2013

init:
  - git config --global core.autocrlf true

install:
- ps: $zipPath = "$($env:TEMP)\Appveyor.NUnit3Logger.zip"
- ps: (New-Object Net.WebClient).DownloadFile('http://www.appveyor.com/downloads/Appveyor.NUnit3Logger.zip', $zipPath)
- ps: 7z x $zipPath -y -o"C:\Tools\NUnit3\bin\addins" | Out-Null
  
environment:
  AjaxControlToolkitTestSiteUrl: http://localhost/TestRunner.aspx

configuration:
  - Release
  - Debug
 
cache:
  - packages -> **\packages.config

before_build:
  - ps: nuget restore

build:
  project: AjaxControlToolkit.sln
  publish_wap: true
  verbosity: minimal
  
after_build:
- ps: '& "AppVeyor\CreateArtifacts.ps1"'
  
artifacts:
  - path: AjaxControlToolkit-nightly-*.zip
  - path: AjaxControlToolkit.StaticResources.zip

test:
  assemblies: bin\$(configuration)\AjaxControlToolkit.Tests.dll
 
services: iis
 
before_test:
- ps: '& "AppVeyor\DeployJasmineSite.ps1"'